### ISSUE TITLE
Marshlight Lake Island with no mobs

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#102]
The Marshlight Lake in Zangarmarsh has an island where there are supposed to be Nagas on, there are no mobs to be found on the island but a couple in the water around the area.

Mob: http://tbc.openwow.com/npc=18089

Screenshot: http://i.imgur.com/V3UaMqh.jpg

Coordinates: X:500.449341 Y: 8397.860352 Z: 20.821306

-Ophius

**Comment by Clearlysql** [comment]
The NPC referred to shouldn't be on this island, however I'm sure there's an other version that should be. Would you be able to find any information on this for me?

**Comment by Ophinkey** [comment]
Album of screenshots from retail for reference: http://imgur.com/a/nwwEk

-Ophius

**Comment by Clearlysql** [comment]
Fixed.
