### ISSUE TITLE
Marshlight Bleeder&#39;s Debuff broken

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#103]
Marshlight Bleeders in Zangarmarsh have a debuff called Vibrant Blood, that should not allow classes with the debuff to be able to stealth, however we were able to stealth with the debuff anyhow. The second part of the debuff with the cast time reduction/damage increase seems to be working properly though.

Screenshot: http://i.imgur.com/1kQyTau.jpg (as you can see on the screenshot that Nicko is in stealth and has the debuff)

.buginfo of one of the Marslight Bleeders:
Coordinates: X:145.665649 Y: 8218.647461 Z: 23.703665
NPC Info: Entry: 18133, GUID: 64764, Name: Marshlight Bleeder

-Ophius

**Comment by Ophinkey** [comment]
The same goes for the Bogflare Needler mob in Zangarmarsh, same type of debuff, same stealth issue.

Screenshot: http://i.imgur.com/OCSpM3R.jpg

Coordinates: 826.842163 Y: 6893.735840 Z: 17.545013
NPC Info: Entry 20197, GUID: 71779, Name: Bogflare Needler

Spell ID: 35328
Spell: http://tbc.openwow.com/spell=35328

-Ophius
