### ISSUE TITLE
Infernal Randomly spawning in Zangarmarsh

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#105]
As the title reads, we were killing some mobs in Zangarmarsh, more specifically Bloodscale Enchantress: http://tbc.openwow.com/npc=18088 and a random infernal looking mob spawned in the middle of nothing and quickly dissapeared again, this happened twice, managed to get a screenshot first time, and a .buginfo second time.

Screenshot: http://i.imgur.com/7wzAgnM.jpg

Coordinates: X: 449.527435 Y: 8098.237793 Z: 19.026600
NPC Info: Entry: 20061, GUID: 8, Name: Frostbite Invisible Stalker

-Ophius

**Comment by Clearlysql** [comment]
These are dev NPC's used for way too many things for me to even describe and it would be a waste of time to figure out what this one actually does. However those should be invisible to the player so thank you for reporting this.

**Comment by Ophinkey** [comment]
This may or may not have something to do with issue #106 we found that the infernals were sometimes following the rogue around and hitting the player.

**Comment by Clearlysql** [comment]
Fixed.
