### ISSUE TITLE
Wrekt Slaves deal alot of damage

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#107]
the Wrekt Slaves of Zangarmarsh seems to deal alot of damage compared to the mobs in the same areas.

Coordinates: X: 458.013489 Y: 8090.853516 Z: 18.635626
NPC Info: Entry: 18123, GUID: 64354, Name: Wrekt Slave

-Ophius

**Comment by Sdyessdev** [comment]
Because....

It's time to get wrekt.

**Comment by Clearlysql** [comment]
Confirmed to have more than double the melee attack damage compared to their slavedrivers.

They also do not use any of the spells they should use, especially not their Shared Bonds which is iconic for this particular npc. http://www.wowhead.com/npc=18123/wrekt-slave#abilities

**Comment by Clearlysql** [comment]
Nerfed their damage quite a bit. Will be applied on next restart.
