### ISSUE TITLE
[NPC] Report all spawnpoint related issues here.

### ISSUE THREAD

**Issue by Clearlysql** [NetherstormTeam/IssueTracker#112]
This does NOT include pathing issues.

To make it easier for devs, tiny little issues like mobs standing underneath ground/having a weird spawnpoint, please post GUID, current spawnpoint/coordinates and link the issue in this thread.

In the fixed pos. please only include the coordinate(s) that should be changed and not the entire coordinate sequence to make it a bit easier to deal with.

GUID: 13170
Current pos: x-532.145020 y-2988.939941 z93.147400
Fixed pos: z93.457817

**Comment by Ophinkey** [comment]
http://i.imgur.com/evP9dFV.jpg

Coordinates: X: 924,209656 Y:2265.635498 Z: 312.708344
NPC Info: Entry: 18728, GUID: 96999, Name: Doom Lord Kazzak

**Comment by Ophinkey** [comment]
http://i.imgur.com/V0vcXRC.jpg

Coordinates: X: 366.143097 Y: 2161.464844 Z: 119.706238
NPC Info: Entry: 16946 GUID: 58976, Name: Mo'arg Forgefiend

Seems to have a weird pattern walking on/off of the forge as seen on the screenshot.

**Comment by Ophinkey** [comment]
http://i.imgur.com/bzjkEjZ.jpg

Stands halfly underground.

Coordinates: X: -534.614929 Y: 4866.050781 Z: 34.299339
NPC Info: Entry: 20679, GUID: 86006, Name: Aylaan the Waterwalker.

Note: checked the other Dreghood quest mobs throughout the village, none of them seem to have the same issue.

-Ophius

**Comment by Ophinkey** [comment]
#169 #170 #171

**Comment by Ophinkey** [comment]
#136

**Comment by Ophinkey** [comment]
#186

**Comment by Ophinkey** [comment]
#189

**Comment by Ophinkey** [comment]
#192

**Comment by Ophinkey** [comment]
#201

**Comment by Ophinkey** [comment]
#208

**Comment by Ophinkey** [comment]
#210
