### ISSUE TITLE
Uzzek missing at the Far Watch Post

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#115]
Uzzek, the guy that starts and ends Path of Defense (quest fordefensive stance for warriors) is missing at his position at the Far Watch Post in The Barrens.

Npc: http://tbc.openwow.com/npc=5810

**Comment by Clearlysql** [comment]
No he's not.
![wowscrnshot_042516_195057](https://cloud.githubusercontent.com/assets/12024073/14793373/0c123004-0b1f-11e6-81f3-c87b072afc4c.jpg)
