### ISSUE TITLE
The Summoning Quest

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#117]
The Summoning warrior quest seems to be bugged, the NPC has to summon some wind elemental, he walks from his hut, casts a spell, things shake up, and then he just walks back and nothing happens, rendering the player unable to complete the quest.

Quest: http://tbc.openwow.com/quest=1713

Video: https://www.youtube.com/watch?v=v5zXh_QvEDk

-Ophius

**Comment by Sdyessdev** [comment]
Fixed, working on PTR.
