### ISSUE TITLE
Salvageable Wood weird spawn

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#121]
A piece of salvageable wood has a weird spawnpoint in Hellfire Peninsula.

Screenshot: http://i.imgur.com/E8LrNKS.jpg

Coordinates: X: -139.918304 Y: 2626.218262 Z: 46.080437

-Ophius

**Comment by Clearlysql** [comment]
Did .gob del 23767. Too lazy to make an SQL for it. But if you really really want one let me know.
