### ISSUE TITLE
Kil'Jaeden Reaver (non-interactable)

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#123]

**Comment by Ophinkey** [comment]
Coordinates: X: 953.936951 Y: 2268.501221, Z: 407.853577
NPC Info: Entry: 22389, GUID: 78716, Name: Kil'Jaeden Reaver (non-interactable)

this mob's abit weird, might just be the name that needs to be changed, removing non-interactable, but it seems quite off.

Screenshot: http://i.imgur.com/ivAONah.jpg

-Ophius

**Comment by Clearlysql** [comment]
IIRC there should be a Fel Reaver there however it's stationary and can't be killed or attacked, or targeted. Could you try this with GM off and leaving and returning to the grid? It has the appropriate flags.
