### ISSUE TITLE
Facing sideways after entering The Dark Portal

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#124]
As the title reads, after you enter The Dark Portal from Blasted Lands through to Hellfire Peninsula, you turn sideways instead of head first.

Video: https://www.youtube.com/watch?v=i6FakC3RVTs

-Ophius

**Comment by Clearlysql** [comment]
Fixed. On a side note, are you supposed to spawn that far out, so close to the edge?

**Comment by Sdyessdev** [comment]
@Clearlysql Should this be closed?

**Comment by Clearlysql** [comment]
Also fixed positioning a bit. Now I'm done.
