### ISSUE TITLE
Dark Portal Thrallmar guard hitting alliances

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#125]
Dark Portal Thrallmar guards are hostile towards alliances, so when going down the stairs to talk to the alliance questgivers, you are immediatly entering combat with a thrallmar guard, leaving you to either kill him, or quickly turn in and run away.

Video: https://www.youtube.com/watch?v=5jastdjIDMU

Coordinates: X: -239.766602, Y: 1017.180176 Z: 58.494858
NPC Info: Entry: 16580, GUID: 57492, Name: Thrallmar Grunt

-Ophius

**Comment by Ophinkey** [comment]
Note: This is NOT an issue for Horde side, they do not aggro an alliance guard in the same manner.

-Ophius

**Comment by Clearlysql** [comment]
Fixed it.
