### ISSUE TITLE
&#34;Hellfire Combat Dummy Small&#34;

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#131]
There&#39;s some weird Hellfire Combat Dummy Small placed in the Expedition Armory, they die from one hit and are just weirdly placed near Arch Mage Xintor&#39;s spawn.

Coordinates: X: -1310.438232 Y: 2769.844482 Z: -27.125494
NPC Info: Entry: 17060, GUID: 86051, Name: Hellfire Combat Dummy Small

-Ophius

**Comment by Clearlysql** [comment]
Those are supposed to be there, however I'm fairly certain they are not supposed to be killable. I added missing dummies to this area as well. Leaving this open until I've fixed the rest.
