### ISSUE TITLE
Bleeding Hollow Worg weird position.

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#136]

**Comment by Ophinkey** [comment]
A Bleeding Hollow Worg has a weird spawn point/positioning.

Screenshot: http://i.imgur.com/IXbZSM3.jpg

Coordinates: X: -1103.496948 Y: 1942.167236 Z: 74.507721
NPC: Entry: 19423, GUID: 69466, Name: Bleeding Hollow Worg

**Comment by Clearlysql** [comment]
Fixed.
