### ISSUE TITLE
Mission: The Abyssal Shelf

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#142]
Seems to be an issue when picking up Mission: The Abyssal Shelf from Wing Commander Gryphongar, that makes the system think that she is the taxi stand, so when you pick it up, you get a message saying &#34;You are to far away from the taxi stand!&#34;

Screenshots: http://imgur.com/a/05dg9

Coordinates: X: 315.497040, Y: 1443.176025 Z: 0.885934
NPC Info: Entry: 20232, GUID: 96985, Name: Wing Commander Gryphongar

-Ophius

**Comment by Clearlysql** [comment]
Discovered duplicate entry script executed on quest start. I deleted it, please check if this works any better now of if I need to investigate further.

**Comment by Jiinkey** [comment]
https://streamable.com/is4d
still doesn't seem to work.
