### ISSUE TITLE
Sedai's Corpse

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#145]
Sedai&#39;s Corpse in Hellfire Peninsula seems to be standing up with full hp, hes supposed to be lying down, with no HP.

Screenshot: http://i.imgur.com/SeRKugT.jpg

Coordinates: X: 192.677917 Y: 4154.153320 Z: 74.549886
NPC Info: Entry: 16852, GUID: 86002, Name: Sedai&#39;s Corpse

-Ophius

**Comment by Clearlysql** [comment]
Fixed. Run a QA after next restart.

**Comment by Ophinkey** [comment]
http://i.imgur.com/cKJxF2r.jpg

still standing up, dead now though.

**Comment by Clearlysql** [comment]
Implemented possible fix. Please check this after restart.
