### ISSUE TITLE
Mag'har Hunters not dismounting in combat

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#147]
The Mag&#39;har Hunters in Hellfire Peninsula currently doesn&#39;t dismount when engaged into combat.

Screenshot: http://imgur.com/BhSwSh6

Coordinates: X: 259.653687 Y: 3759.703369 Z: 180.502823
NPC Info: 16912, GUID: 58673, Name Mag&#39;har Hunter

-Ophius

**Comment by Ophinkey** [comment]
Note: When the hunter dies, the mount does aswell.

Screenshot: http://i.imgur.com/jC8fUUl.jpg

**Comment by Clearlysql** [comment]
Test this after restart. The mounting after death or leaving combat is grid related.

**Comment by Jiinkey** [comment]
Fixed, dismount works on all mag'har hunters.
