### ISSUE TITLE
[Player/Combat] Pulling with Right Click

### ISSUE THREAD

**Issue by LightningBlade** [NetherstormTeam/IssueTracker#16]
Trigger NPC: Young Wolf - http://tbc.openwow.com/npc=299

Description: I managed to pull a creature of beast type, being 15 yards away from it as a level 1 warrior.

How to Reproduce: Stand around 10 - 20 yards from the creature, and right click on it, if it does not run to you, move a bit closer

**Comment by Nevarian** [comment]
Does not work with humanoids as far as I could see. Only with beasts.

**Comment by jameyboor** [comment]
Fixed.
