### ISSUE TITLE
[Core] UNIT_FLAG_NOT_SELECTABLE doesn't work.

### ISSUE THREAD

**Issue by Clearlysql** [NetherstormTeam/IssueTracker#162]
Flag 33554432, UNIT_FLAG_NOT_SELECTABLE should render the NPC unselectable through /target and mouse selection. At the moment it seems to do nothing.

**Comment by Sdyessdev** [comment]
Have you checked other creatures with this flag?

**Comment by Clearlysql** [comment]
Yes. At least three different NPC's, even those with this flag alone. Doesn't do anything.

**Comment by Clearlysql** [comment]
Related to #159. Just FYI.
