### ISSUE TITLE
Strange Shiny Object under ground in Hellfire

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#167]
There is a strange shiny object under the ground in hellfire, but not far enough down to for the shiny stuff to not be visible.

Screenshot: http://i.imgur.com/TQfapRV.jpg

Coordinates: X: -524.136963, Y: 4877.773926 Z: 34.684410

I think it may be a Sha'naar Relic for the Sha'naar Relics quest.

Quest: http://tbc.openwow.com/quest=9430
Item: http://tbc.openwow.com/item=23642

-Ophius

**Comment by Sdyessdev** [comment]
Fixed
