### ISSUE TITLE
Avruu's Orb bugged

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#187]
The Avruu's Orb quest is currently bugged, when the item is used on the big orb on the ground, the cast finishes, but the Wind Elemental is currently not spawned after the cast finishes.

NPC: http://tbc.openwow.com/npc=17085
Item: http://tbc.openwow.com/item=23580
Spell: http://tbc.openwow.com/spell=29764
Quest: http://tbc.openwow.com/quest=9418

Screenshots: http://imgur.com/a/Jh1gg

-Ophius

**Comment by Clearlysql** [comment]
Test this after server restart.

**Comment by Jiinkey** [comment]
Interacting with the orb is still possible, still doesnt spawn Aeranas.

Screenshot: http://imgur.com/a/SfOjR

**Comment by Pragma8123** [comment]
Test this after restart.

**Comment by Pragma8123** [comment]
Fixed
