### ISSUE TITLE
Fields of Grief Quest, Pumpkin Spawn time.

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#19]
Fields of Grief Quest. Pumpkin re-spawn time took about 8 minutes. I believe they normally take about 3-4 to match the NPC  spawn rates, not entirely sure.

**Comment by JppTheInsane** [comment]
Comment from 2.4.1 on wowhead says about 5 minutes.
http://www.wowhead.com/item=2846/tirisfal-pumpkin#comments

**Comment by Clearlysql** [comment]
Halved the respawn time on object. Was originally set to 700.
