### ISSUE TITLE
Tagar Spinebreaker respawns very fast

### ISSUE THREAD

**Issue by Ophinkey** [NetherstormTeam/IssueTracker#199]
Tagar Spinebreaker in Hellfire Peninsula seems to be respawning extremely fast for an elite mob.

X: -130.321030, Y: 2598.195312, Z: 45.833458
NPC info: Entry: 19443, GUID: 85987, Name: Tagar Spinebreaker

-Ophius

**Comment by Clearlysql** [comment]
Missing weapon: 12784

Followup: How long respawn time should he approximately have?

**Comment by Ophinkey** [comment]
I flew around for 35 minutes doing nothing but target macros looking for this guy and quickly got target of a dead Tagar Spinebreaker within the first few minutes, after that I flew around looking for his respawn and exactly 30 minutes later (plus minus 20 seconds) i got target of him again (note: he was dead when I found him first, hence the 20 secondsish).

-Ophius
