### ISSUE TITLE
[Creature/AI] Bonechewer Raider

### ISSUE THREAD

**Issue by Nevarian** [NetherstormTeam/IssueTracker#20]
Creature should dismount when summoning his wolf.

See gif:
https://gyazo.com/b22c9d94a3fbb24dd90a31b268e3c38b

Entry: 16925

**Comment by Clearlysql** [comment]
Missing creature_ai_scripts for dismount.

**Comment by Clearlysql** [comment]
Added dismount event AI script. The NPC now dismounts on aggro as intended.
