### ISSUE TITLE
Thrallmar Wolf Rider standing on a fel reaver part

### ISSUE THREAD

**Issue by Ophinkey** [NetherstormTeam/IssueTracker#210]
At Reaver's Fall in Hellfire Peninsula theres a Thrallmar Wolf Rider standing on top of a fel reaver part.

Screenshot: http://i.imgur.com/5ifgyTb.jpg

Coordinates: X: -64.324081 Y: 2196.135010 Z: 104.288589
NPC Info: 16599, GUID: 57592, Name: Thrallmar Wolf Rider

-Ophius

**Comment by Clearlysql** [comment]
Need confirmation whether this should be intended or not.

**Comment by Ophinkey** [comment]
http://i.imgur.com/24EAI0i.jpg
after a bit of research I found it to be intended.
