### ISSUE TITLE
Random Ancestral Spirit Wolf standing the middle of nothing

### ISSUE THREAD

**Issue by Ophinkey** [NetherstormTeam/IssueTracker#217]
A random Ancestral Spirit Wolf is standing in the middle of nothing, does nothing, and is supposed to be used for the A Spirit Guide quest.

Screenshot: http://i.imgur.com/e7rumrL.jpg

Coordinates: X: 103.674271 Y: 3943.549316 Z: 76.409218
NPC Info: Entry: 17077, GUID: 20, Name: Ancestral Spirit Wolf

**Comment by Clearlysql** [comment]
Deleted from the game.
