### ISSUE TITLE
Tamed Ravager unfriendly even though im neutral with Mag'har

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#219]
The Magh'har Hunters in Hellfire Peninsulas pets, Tamed Ravagers, seem to stay unfriendly even though I reached neutral reputation with Mag'har.

Screenshot: http://i.imgur.com/GmG7Cuu.jpg

Coordinates: X: 300.450226 Y: 3788.774658 Z: 180.802505
NPC Info: Entry: 19461, GUID: 9, Name: Tamed Ravager.

**Comment by Ophinkey** [comment]
Definetly has something to do with #154

-Ophius

**Comment by Ophinkey** [comment]
http://i.imgur.com/cSWXwMF.jpg

On retail one hunter has one pet, the one that has the <Mag'har Hunter's Pet>

**Comment by Jiinkey** [comment]
Should just be assigned to the Mag'har faction should be easily done

**Comment by Enether** [comment]
Seems fixed.
