### ISSUE TITLE
Floating Skull at Reaver's Fall missing

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#222]
The Floating Skull NPC at Reaver's Fall is currently missing.

Screenshot from retail: http://i.imgur.com/p0xswI2.jpg
Screenshot: http://imgur.com/iOX9bM4

NPC: http://tbc.openwow.com/npc=21365

-Ophius

**Comment by Ophinkey** [comment]
http://i.imgur.com/1znwQga.jpg <aerial view.

**Comment by Clearlysql** [comment]
Missing display for skull. Can't do much without it, sadly.

**Comment by Clearlysql** [comment]
Test after next restart.
