### ISSUE TITLE
[Creature/Faction] Thrallmar Grunt

### ISSUE THREAD

**Issue by Nevarian** [NetherstormTeam/IssueTracker#23]
Has flag UNIT_FLAG_PASSIVE & UNIT_FLAG_OOC_NOT_ATTACKABLE (don't know why), which makes them passive to the alliance.  Also has a weird faction that makes them neutral instead of agressive to alliance players, should be 1729 like all other thrallmar creatures..

Proposed Fix:
`UPDATE creature_template SET UnitFlags=0 AND FactionAlliance=1729 AND FactionHorde=1729 WHERE entry=16580;`

**Comment by jameyboor** [comment]
Fixed.

**Comment by jameyboor** [comment]
Not so fixed after all.

**Comment by Nevarian** [comment]
Fixed.
