### ISSUE TITLE
The Demoniac Scryer

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#238]
The Demoniac Scryer quest seems very bugged to say the least. First of all when the quest is started and the Scryer spawns, it starts moving around the area, then as the quest progresses, invisible things with visible names show up, "Magic Sucker Device Butress" show up and they also start moving around.

Screenshots: http://imgur.com/a/T07lF

Coordinates: X: -216.103409 Y: 3215.611084 Z: -74.142235
NPC Info: Entry: 22258, GUID: 200111, Name: Demoniac Scryer

Quest: http://tbc.openwow.com/quest=10838
NPC: http://tbc.openwow.com/npc=22258
Item: http://tbc.openwow.com/item=31606
Spell: http://tbc.openwow.com/spell=38707

-Ophius

**Comment by Clearlysql** [comment]
Test this after server restart.
