### ISSUE TITLE
Vorakem Doomspeaker

### ISSUE THREAD

**Issue by Ophinkey** [NetherstormTeam/IssueTracker#240]
Vorakem Doomspeaker, a rare in Hellfire Peninsula seems to be missing his two weapons. (see: http://www.wowhead.com/npc=18679/vorakem-doomspeaker#screenshots)

Screenshot: http://i.imgur.com/qBIckXU.jpg

Coordinates: X: 360.198486 Y: 3475.469727 Z: 62.220573
NPC Info: 18679, GUID: 99252, Name: Vorakem Doomspeaker

-Ophius

**Comment by Clearlysql** [comment]
Gave him http://www.wowhead.com/item=23054/gressil-dawn-of-ruin
Closest thing I could find that wasn't http://www.wowhead.com/item=22736/andonisus-reaper-of-souls

Let me know if it looks alright.
