### ISSUE TITLE
Warlock - Demonic Embrace

### ISSUE THREAD

**Issue by Nicko11** [NetherstormTeam/IssueTracker#244]
It's supposed to add 15% stamina and remove 5% spirit at max rank, this is not the case as it does not work in any of the ranks.

**Comment by Blumfield** [comment]
https://streamable.com/962x

not sure if i'm doing it wrong but seems fine to me ?

**Comment by Nicko11** [comment]
Was this done on the dev server or test server? I'm unable to make it work on my lock atleast.

**Comment by Blumfield** [comment]
on my local and ptr, we can't reproduce it, try with a new & clean char

**Comment by Nicko11** [comment]
Alright works on the new lock, i've got no idea what went wrong on the other one.
