### ISSUE TITLE
Magister Aledis

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#248]
Magister Aledis in Hellfire Peninsula seems slightly bugged. The question mark for his quest(s) seem to not appear above him. 

Coordinates: X: -678.785889 Y: 4217.391602 Z: 48.876839
NPC Info: Entry: 20159, GUID: 86873, Name: Magister Aledis

-Ophius

**Comment by Ophinkey** [comment]
Note: This may be in regards to me not having interogated him as I was supposed to, but this option is currently unavailable and I cannot complete the quest.

NPC: http://tbc.openwow.com/npc=20159
Quest: http://tbc.openwow.com/quest=10286

**Comment by Ophinkey** [comment]
Arelion's Secret on Retail: http://imgur.com/a/3TSEJ

**Comment by Pragma8123** [comment]
Magister Aledis already has a ScriptDev2 entry in hellfire_peninsula.cpp that should give him the proper behavior.
I'll investigate this further.
