### ISSUE TITLE
Arelion's Knapsack

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#251]
When opening Arelion's Knapsack in Hellfire Peninsula, you are supposed to loot, Arelion's Knapsack and open the Knapsack in your inventory, however when looting the Knapsack you loot Arelion's Journal and a Box of Stale Candy, however you are meant to loot the actualy Knapsack, and open it inside of your inventory, where when opened, it contains Arelion's Journal, Box of Stale Candy & Ruined Scented Candle.

Screenshots: http://imgur.com/a/TyWBk

Quest: http://tbc.openwow.com/quest=9374

Object: http://tbc.openwow.com/object=184115
Item: http://tbc.openwow.com/item=31955
Journal: http://tbc.openwow.com/item=23339
Box: http://tbc.openwow.com/item=29111
Candle: http://tbc.openwow.com/item=29110

-Ophius

**Comment by Clearlysql** [comment]
Test this after the next restart.

**Comment by Jiinkey** [comment]
Tested, now looting the knapsack yields no loot at all.

**Comment by LightningBlade** [comment]
Can you please re test this?, gave me Box of Stale Candy, and Ruined Scented Candle

**Comment by Clearlysql** [comment]
Fixed flag and dropreq. Test after restart.

**Comment by Jiinkey** [comment]
http://imgur.com/vwKZdb6

not lootable at all now.

**Comment by Clearlysql** [comment]
Okay now it will work. I screwed up before, don't dev while you're tired. Added loot conditions on knapsack and removed stupid flag.

**Comment by LightningBlade** [comment]
Tested, and this now works

**Comment by LightningBlade** [comment]
Oml
xD
