### ISSUE TITLE
Falcon Watch Ranger

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#253]
The Falcon Watch Ranger's seem to lack their normal patrol routes.

Screenshot: http://imgur.com/aR33PbG

Coordinates: X: 671.514893 Y: 4108.886230 Z: 74.343796
NPC Info: Entry: 17282, GUID: 62072, Name: Falcon Watch Ranger

-Ophius

**Comment by Ophinkey** [comment]
Note: Goes for more or less all the rangers in the area.

**Comment by Pragma8123** [comment]
Check on restart

**Comment by Sdyessdev** [comment]
Issue was resolved
