### ISSUE TITLE
Vicious Teromoth

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#260]
The Vicious Teromoths in The Cenarion Thicket in Terokkar Forest seems to be missing. Theres no mobs to be found inside of the village at all, only outside and around the village.

Coordinates: X: -1835.655396 Y: 4645.835449 Z: 9.479223
NPC Info: Entry: 18437, GUID: 65842, Name: Vicious Teromoth

Also some of the Teromoths seem to be having spawn point issues, the one I did the buginfo on is halfly underground.

Screenshot: http://i.imgur.com/ldJQRIw.jpg

-Jiinkey

**Comment by LightningBlade** [comment]
The mob count seems to check out according to videos and cross checking data against other databases.

The Spawn Point issue have been corrected
