### ISSUE TITLE
Empoor / By Any Means Necessary

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#261]
For the quest By Any Means Necessary with Empoor in Terokkar Forest, you don't actually have to interogate him to complete the quest, even though it isn't flagged as complete in the quest log.

Screenshot: http://i.imgur.com/De371Cp.jpg

Coordinates: X: -1935.475708 Y: 4839.518066 Z: 1.312996
NPC Info: Entry: 18482, GUID: 66605, Name: Empoor

Quest: http://tbc.openwow.com/quest=9978

Note: I haven't tested the actual interogation/fighting phase of this quest as I tested this bug first.

**Comment by LightningBlade** [comment]
Quest is no longer complete upon accepted, but the interogation phase is completely missing

**Comment by LightningBlade** [comment]
Fixed
