### ISSUE TITLE
All quests show up with a yellow question mark despite being incomplete

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#262]
All quests I've encountered so far while questing through outlands have been shown as complete when talking to an npc (not with the greyed out question mark, but with the yellow one), this makes the player think you can turn in a quest, despite actually not being able to.

Screenshots: http://imgur.com/a/mS1uq

-Jiinkey

**Comment by Pragma8123** [comment]
This is apparently just how quest gossip worked back in TBC. Issue closed.
