### ISSUE TITLE
The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Pragma8123** [NetherstormTeam/IssueTracker#272]
The actual exorcism event for the quest **_The Exorcism of Colonel Jules_** does not play out. You can talk to Anchorite Barada and he goes through his first few lines of dialogue but does not start the exorcism.

Colonel Jules also seems to have the wrong display ID:
![wowscrnshot_051816_164259](https://cloud.githubusercontent.com/assets/1151479/15374440/6900c7ca-1d18-11e6-8e5b-e8f011b2fd67.jpg)

**GPS**: **X**: -707.211 **Y**: 2754.11 **Z**: 101.675 **Map**:530
**(NPC) Anchorite Barada**: 22431
**(NPC) Colonel Jules**: 22432

**Comment by Pragma8123** [comment]
His DisplayID should be 14533

**Comment by Pragma8123** [comment]
The test server has been patched. Please provide feedback for the quest event here.

**Comment by Sdyessdev** [comment]
Problems:

The quest repeatedly resets itself and never finishes all the way.
Darkness Released should move further out in the room, they only hover around the bed at the moment
The prayer beads have a delay after being cast
The Foul purge slimes spawn too quickly, went OOM handling them all on the 2nd try, first try I was overwhelmed by them
Movement of Colonel Jules is a little wacky

**Comment by Pragma8123** [comment]
Did a complete overhaul of the event. Check on next restart

**Comment by Pragma8123** [comment]
Prayer beads have been fixed
