### ISSUE TITLE
Mobs won't lose aggro

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#274]
After runing away from Render's Camp in Redridge Mountains all mobs keeps following me until I killed them no matter how far away I got they didn't lose aggro.

**Comment by Sdyessdev** [comment]
NPCs still reset, no issues really.

Should add an IsElite() check to https://github.com/Sdyessdev/NetherstormCore/commit/a64990656c8ff935f549ee4a78eb1ad8ffb6f009

**Comment by omghixd** [comment]
You may have to run quite far. that's completely normal :)

**Comment by disastrous94** [comment]
From Render's Camp to Lakeshire?
