### ISSUE TITLE
Apothecary Zelana (Reaver's Fall)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#279]
The Apothecary Zelana NPC at Reaver's Fall currently only says "Greetings *name*" when interacted with, it's supposed to be:
"The Royal Apothecary Society of the Undercity is eager to aid our orc allies here, in Outland. It is an oppotunity to strengthen our bonds, and find new specimens and compounds for study.

Compounds...such as poisons."

Screenshot: http://imgur.com/sQiQeLx

**Comment by LightningBlade** [comment]
This have been corrected
