### ISSUE TITLE
Overlord Hun Maimfist (Reaver's Fall)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#280]
Overlord Hun Maimfist needs to get the /roar emote and while doing the emote he needs to /say:
"We war so that our little ones may live to see a better tommorow! And for them, we destroy the Burning Legion!"

Screenshot from retail: http://imgur.com/FS1oOlh

Coordinates:  X: -60.414516 Y: 2200.399414 Z: 123.239151
NPC Info: Entry: 16576, GUID: 57481, Name: Overlord Hun Maimfist

Note: This happens about once per minute.

**Comment by LightningBlade** [comment]
This have been corrected

**Comment by Jiinkey** [comment]
Needs to be saying it, not yelling it. Reopening.

**Comment by LightningBlade** [comment]
Corrected
