### ISSUE TITLE
[Spell/Mechanics]NPC Bristleback Thornweaver's "Entangling Roots" is not affected by Rogue "Kick"

### ISSUE THREAD

**Issue by Sdyessdev** [NetherstormTeam/IssueTracker#3]
Tested rogue kick, mage counterspell, shaman earthshock, warrior pummel. All abilities fail to interrupt cast.
Entangling Roots (spell=12747)
Bristleback Thornweaver (npc=3261)

**Comment by jameyboor** [comment]
Fuck you, just works.

**Comment by jameyboor** [comment]
Fixed.
