### ISSUE TITLE
[Gossiptext] Overlord Hun Maimfist (Reaver's Fall)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#300]
Overlord Hun Maimfist needs to say:
"Thrallmar needs you, *class*. The warchief needs you. 
Stand ready to do your duty."

Screenshot from retail: http://i.imgur.com/WgSjMn7.jpg

Coordinates: X: -60.414516 Y: 2200.399414 Z: 123.239151
NPC Info: Entry: 16576, GUID: 57481, Name: Overlord Hun Maimfist

Note: Currently just says "Greetings *name*"

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Doesn't work fully, says class instead of the actual class name.

http://i.imgur.com/P2LL6Se.jpg

**Comment by Clearlysql** [comment]
Fixed.
