### ISSUE TITLE
[Gossip Text] Foward Commander To'arch

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#302]
Forward Commander To'arch in Hellfire Peninsula needs to say:
"If you're ever captured by the Legion, tell them "Xar il romath da tidesbi." They will kill you instantly for insulting their god, saving you intolerable torture or worse..."
upon interaction.

Screenshot: http://i.imgur.com/Oe480E4.jpg

Coordinates: X: -23.433001, Y: 2137.856445, Z: 113.090599
NPC Info: Entry: 19273, GUID: 68839, Name: Forward Commander To'arch

Note: right now he only says "Greetings *name*"

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
