### ISSUE TITLE
[Gossip Text] Watch Commander Krunk

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#303]
Watch Commander Krunk in Thrallmar, Hellfire Peninsula needs to say:
"You look lost, *class*. Don't make me put you to work on the walls with the other peons."
upon interaction

Screenshot: http://i.imgur.com/XgRyduA.jpg

Coordinates: X: 129.911194 Y: 2705.121094 Z: 88.173576
NPC Info: Entry: 16584, GUID: 57557, Name: Watch Commander Krunk

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
