### ISSUE TITLE
[Gossip Text] Far Seer Regulkut

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#304]
Far Seer Regulkut is supposed to say:
"Well met, *class*. Your arrival in Thrallmar could not have occured at a better time. The Warchief is depending on us, since he cannot be here himself."
upon interaction.

Screenshot: http://i.imgur.com/LZMJfAg.jpg

Coordinates: X: 175.907837 Y: 2737.350830 Z: 87.955322
NPC Info: Entry: 16574, GUID: 57479, Name: Far Seer Regulkut

Right now she just says: "Greetings *name*"

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
