### ISSUE TITLE
[Gossiptext] Felannia

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#305]
Felannia in Thrallmar, Hellfire Peninsula is supposed to say:
"Have you honed your skills enough to learn what I have to teach?"
upon interaction.

Screenshot: http://i.imgur.com/ieNCWWS.jpg

Coordinates: X: 241.457932 Y: 2837.382568, Z: 145.104034
NPC Info: Entry: 18753, GUID: 67026, Name: Felannia

Note: currently just says "Greetings *name*"

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
