### ISSUE TITLE
[Gossip Text] Angela "The Claw" Kestrel

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#306]
Angela "The Claw" Kestrel in Thrallmar, Hellfire Peninsula is supposed to say:
"<Angela coos to the felhunter again before turning her attention to you.>

Jir'see's always been smaller than the other Felhunters, but that's never bothered him. And Outland's going to change all that, right Jir'see?

Momma's little angel is going to grow up to be a big, fierce felhunter, yes he is!"
upon interaction.

Screenshot: http://i.imgur.com/d9iscpA.jpg

Coordinates: X: 233.125397 Y: 2831.235840 Z: 179.740784
NPC Info: Entry: 17002, GUID: 86025, Name: Angela "The Claw" Kestrel

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
