### ISSUE TITLE
Pilgrim Gal'ressa

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#307]
Pilgrim Gal'ressa in Falcon Watch, Hellfire Peninsula needs to say:
"I think I'm beginning to regret undertaking this pilgrimage. I anticipated that the road would be rough and I'm no stranger to travel, but I wasn't prepared for the rigors of Outland.

On top of everything else, that Taleris seems to want to push me out of here before I've regained my strength completely."

Screenshot: http://i.imgur.com/dDtEQMi.jpg

Coordinates: X: -648.523682 Y: 4177.198918 Z: 68.471412
NPC Info: Entry: 17046, GUID: 59423, Name:  Pilgrim Gal'ressa

Note: currently just says "Greetings *name*"

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
