### ISSUE TITLE
[Gossip Text] Wanted Poster (Falcon Watch)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#310]
The Wanted Poster @ Falcon Watch, Hellfire Peninsula needs to say,
"This sign contains various announcements and notices of rewards."
upon interaction.

Screenshot from our server: http://i.imgur.com/vinewSp.jpg

Screenshot from retail: http://i.imgur.com/e47MCyz.jpg

**Comment by Sdyessdev** [comment]
Check your screenshots pls

**Comment by Jiinkey** [comment]
So many screenshots i accidentially uploaded the same one twice, correct one for retail is: http://i.imgur.com/e47MCyz.jpg

**Comment by Clearlysql** [comment]
Need GUID of wanted poster as well as a WoWHead link to it. Missing conditions, obviously.

**Comment by Jiinkey** [comment]
22072, Entry 181638 - [Wanted Poster X:-595.403015 Y:4091.239990 Z:91.873703 MapId:530]

http://legion.wowhead.com/object=181638/wanted-poster

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Fixed.
