### ISSUE TITLE
Orb of Translocation (Falcon Watch)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#311]
The Orb of Translocation @ Falcon Watch, Hellfire Peninsula is currently not teleporting the player(s) on top of the tower as it should do.

Video: https://streamable.com/akw1

Note: doesn't work on top of the tower either.

**Comment by Sdyessdev** [comment]
Can you show me what it does on retail pls?

**Comment by Jiinkey** [comment]
Clip of retail: https://streamable.com/dtdp

**Comment by Pragma8123** [comment]
Right-clicking the object gives the error "Another action is in progress"

**Comment by Clearlysql** [comment]
Require GUID of both objects.

**Comment by Jiinkey** [comment]
#395

**Comment by Pragma8123** [comment]
Check next restart

**Comment by Pragma8123** [comment]
Fixed
