### ISSUE TITLE
Gorkan Bloodfist

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#312]
Gorkan Bloodfist in Mag'har Post, Hellfire Peninsula is supposed to say:
"You are welcome among us, *class*. At least for the time being.

Screenshot: http://i.imgur.com/bwWIX04.jpg

Coordinates: X: 506.711212 Y: 3882.148926 Z: 191.797729
NPC Info: Entry: 16845, GUID: 57980, Name: Gorkan Bloodfist

Note: currently just saying "Greetings *name*."

**Comment by Sdyessdev** [comment]
Fixed, check on next restart

**Comment by Jiinkey** [comment]
Fixed, closed.
