### ISSUE TITLE
Earthcaller Ryga

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#313]
Earthcaller Ryga in Mag'har Post, Hellfire Peninsula needs to say:
"May the spirit guide you, *race*."
upon interaction.

Screenshot: http://i.imgur.com/GZvrwfL.jpg

Coordinates: X: 506.711212 Y: 3882.148926 Z: 191.797729
NPC Info: Entry: 17123, GUID: 59522, Name: Earthcaller Ryga

Note: Currently just says "Greetings *name*"

**Comment by Sdyessdev** [comment]
Fixed, check on next restart

**Comment by Jiinkey** [comment]
I spelled wrong, needs to be spirit*s* not just spirit. Please correct :)

**Comment by Clearlysql** [comment]
Fixed.
