### ISSUE TITLE
Provisioner Braknar

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#314]
Provisioner Braknar in Mag'har Post, Hellfire Peninsula needs to say:
"Strength to the Clans, *class!* What brings you here?"
upon interaction.

Screenshot: http://i.imgur.com/M1FppN7.jpg

Coordinates: X: 488.911346 Y: 3875.912109 Z: 193.743393
NPC Info: Entry: 16848, GUID: 58016, Name: Provisioner Braknar

Note: currently says "Greetings *name*" upon interaction

**Comment by Sdyessdev** [comment]
Fixed, check on next restart

**Comment by Jiinkey** [comment]
http://i.imgur.com/TBbPfcO.jpg need to say player class, not just "class" aka for me in screenshot should say warrior.

**Comment by Sdyessdev** [comment]
hahaha man i swear i put $c instead of class, i'll fix it in a bit

**Comment by Clearlysql** [comment]
Fixed
