### ISSUE TITLE
Stone Guard Ambelan

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#315]
Stone Guard Ambelan at Spinebreaker Post, Hellfire Peninsula is supposed to say:
"Keep your voice low and your eyes open, *Name*. We're sorrounded by enemies out here.
upon interaction.

Screenshot: http://i.imgur.com/uvM4ChS.jpg

Coordinates: X: -1310.055420 Y: 2371.209717 Z: 88.527771
NPC Info: Entry: 19332, GUID: 68914, Name: Stone Guard Ambelan)

Note: Currently says "Greetings *name*"

**Comment by Sdyessdev** [comment]
Fixed, check on next restart

**Comment by Jiinkey** [comment]
Fixed, closed.
