### ISSUE TITLE
[Gossiptext] Captain Darkhowl

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#316]
Captain Darkhowl at Spinebreaker Post, Hellfire Peninsula is supposed to say:
"Spinebreaker Post is a great place to be stationed! The Bleeding Hollow aberrations are so close you can smell their foul blood! What better place to gather vengeance from a clan that has forsaken its brethren and made a pact with demons?".

Screenshot: http://i.imgur.com/ANwZUZb.jpg

Coordinates:  X: -1315.670288 Y: 2375.387451 Z: 88.305260
NPC Info: Entry: 22107, GUID: 77641 Name: Captain Darkhowl

Note: Currently says "Greetings *name*"

**Comment by Sdyessdev** [comment]
Fixed, check on restart

**Comment by Jiinkey** [comment]
Fixed, closed.
