### ISSUE TITLE
Apothecary Albreck

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#318]
Apothecary Albreck at Spinebreaker Post, Hellfire Peninsula is supposed to say:
"I am told that the dust and heat of Hellfire Peninsula is quite irritating... I would not know, but I will turst my esteemed, and still living, allies.".

Screenshot: http://i.imgur.com/JMmmmTj.jpg

Coordinates: X: -1332.063843 Y: 2381.884033 Z: 88.953415
NPC Info: Entry: 21279, GUID: 74544, Name: Apothecary Albreck

Note: Currently says "Greetings name"

**Comment by Sdyessdev** [comment]
Fixed
