### ISSUE TITLE
Thrallmar Peons (Zzz's)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#319]
The Two Thrallmar Peons at Spinebreaker Post, Hellfire Peninsula that is sleeping underneath a hut, doesn't have the Zzz's going over their head to animate their sleep.

Screenshot from retail: http://i.imgur.com/J6Nc9fm.jpg

Coordinates: X-1334.956421 Y: 2371.471680 Z: 88.950356
NPC Info: Entry: 16591, GUID 57579 Name: Thrallmar Peon

Coordinates: X-1334.956421 Y: 2371.471680 Z: 88.950356
NPC Info: Entry: 16591, GUID 57580 Name: Thrallmar Peon

**Comment by Clearlysql** [comment]
Check after restart.

**Comment by Jiinkey** [comment]
Zzz's work now.
