### ISSUE TITLE
[Creature/AI] Entering Instance

### ISSUE THREAD

**Issue by LightningBlade** [NetherstormTeam/IssueTracker#32]
Upon entering a dungeon, any chasing AI will run to the dungeon portal and stand still until Combat has reset ( Which is first does when another player aggros them ( or the player goes out side of the dungeon )

Note: Does not happen everytime, trying to figure out the exact reason

**Comment by Sdyessdev** [comment]
Can you explain this a little more?

**Comment by LightningBlade** [comment]
When one of the testers went inside the dungeon, I a few seconds later went to the entrance, where 4 Shattered Hand Berserkers stood inside the instance portal and wouldn't reset until I forced aggro and took GM on

**Comment by LightningBlade** [comment]
What I did to Reproduce

1. Be alone in the Zone
2. Pull the mob and then run into the instance ( https://gyazo.com/30ea8aa795a2b28aab31f1a6037ea001 )
3. Type the command .tele honorhold ( Running back out will reset the mob )
4. Return to the outside and watch the result ( https://gyazo.com/9d1d624712fa140b0f9743118431ded0 )

**Comment by Sdyessdev** [comment]
Can you test this with a hearthstone instead of .tele? Interested if it has the same result.
