### ISSUE TITLE
Zezzak

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#320]
Zezzak at Spinebreaker Post, Hellfire Peninsula is supposed to say:
"There are mysteries in this place that we, the orcs, are desperate to uncover. Mysteries of our past, mysteries of our future, and mysteries that offer glimpses inside us.

It is my hope to pierce these mysteries... will you walk that path with me?"

Screenshot: http://i.imgur.com/P2sZiXv.jpg

Coordinates: X: -1337.073486 Y: 2355.368652 Z: 88.953812
NPC Info: Entry: 22231, GUID: 77945, Name: Zezzak

Note: Currently says "Greetings name"

**Comment by Sdyessdev** [comment]
Fixed
