### ISSUE TITLE
[Gossiptext] Prospector Murantus

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#325]
Prospector Murantus in Honor Hold, Hellfire Peninsula is currently not available to talk at all upon interaction, he is supposed to say:
"If you're looking for work, *class*, grab yourself a pick and get to digging. There're ruins out there as far as the eye can see!"
when interacted with.

Screenshot: http://i.imgur.com/4kNzDaW.jpg

Screenshot from retail: http://i.imgur.com/WgDypW9.jpg

Coordinates: X: -670.388000 Y: 2595.354736 Z: 85.726082
NPC Info: Entry: 16832, GUID: 57905, Name: Prospector Murantus

**Comment by Pragma8123** [comment]
Fix submitted, check on next restart

**Comment by Jiinkey** [comment]
Fixed, closed.
