### ISSUE TITLE
Dumphry 

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#329]
Dumphry in Honor Hold, Hellfire Peninsula is currently not offering to train in blacksmithing as he is supposed to.

Screenshot: http://i.imgur.com/qCcAWmJ.jpg

Screenshot from retail: http://i.imgur.com/JFdH5kG.jpg

**Comment by Clearlysql** [comment]
Need NPC entry

**Comment by Jiinkey** [comment]
Coordinates: X: -590.793762 Y: 2895.815674 Z: 59.204132
NPC Info: Entry: 21209, GUID: 74397, Name: Dumphry

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
