### ISSUE TITLE
Very weird flying Deranged Hellboar

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#330]
I fell across a very weird flying deranged hellboar on some crazy space mission.

Screenshot: http://i.imgur.com/6Cco5yq.jpg

Coordinates: X: -528.614258 Y: 2882.646484 Z: 41.846573
NPC Info: Entry: 16863, GUID: 58084, Name: Deranged Hellboar

**Comment by Clearlysql** [comment]
One may say... That this Hellboar is...

Deranged.


Deleted him.
