### ISSUE TITLE
Stormwind Infantry/Honor Hold Defender

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#334]
The Stormwind Infantry and Honor Hold defenders hitting the fel reaver parts on the ground near Field Marshal Rohamus is currently using the wrong weapon models for doing so, they are using their normal counter parts weapons instead of hammers.

Screenshot: http://i.imgur.com/ypoVJQD.jpg

Screenshot from retail: http://i.imgur.com/qiLm6un.jpg

Number 1:
Coordinates: X: -692.187744 Y: 1879.026367 Z: 63.512707
NPC Info: Entry: 16842, GUID: 57933, Name: Honor Hold Defender

Number 2:
Coordinates: X: -692.18744 Y: 1879.026367 Z: 63.512707
NPC Info: Entry: 16864, GUID: 58140, Name: Stormwind Infantry

Number 3:
Coordinates: X: -692.18744 Y: 1879.026367 Z: 63.512707
NPC Info: Entry: 16864, GUID: 58139, Name: Stormwind Infantry

Number 4: 
Coordinates: X: -692.18744 Y: 1879.026367 Z: 63.512707
NPC Info: Entry: 16864, GUID: 58138, Name: Stormwin Infantry

**Comment by Clearlysql** [comment]
Could I get a close up on the hammer they're wielding? Alternatively a link to a lookalike weapon with the same display, which would save me some searching.

**Comment by Jiinkey** [comment]
well fml. Looking for the correct weapon model for 20-25 minutes, the model we need is the standard blacksmith hammer. Check http://www.wowhead.com/item=2048/anvilmar-hammer same model as.

http://imgur.com/a/y13aB

**Comment by Clearlysql** [comment]
Check after restart.

**Comment by Jiinkey** [comment]
http://imgur.com/a/DMn8T not wielding anything now.
