### ISSUE TITLE
[Gossiptext] Legassi

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#335]
Legassi near the crashed Zeppelin in Hellfire Peninsula needs to say:
"Horrible... just horrible!

We were minding our own buisness on our way from Area 52 in Netherstorm and they shot us down! I knew we shouldn't have taken that shortcut to get to Terokkar Forest!"
upon interaction

Screenshot: http://i.imgur.com/7SoySps.jpg

Coordinates: X: -1092.912598 Y: 2994.770508 Z: 8.190489
NPC Info: Entry: 19344, GUID: 68960, Name: Legassi

Note: Currently just says "Greetings *name*"

**Comment by Pragma8123** [comment]
Fix submitted, check next restart

**Comment by Jiinkey** [comment]
Fixed, closed.
