### ISSUE TITLE
Telhamat Protector/Talaara

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#337]
A Telhamat Protector in Telhamat, Hellfire Peninsula is standing almost literally ontop of Talaara, and is not supposed to be anywhere nearby.

Screenshot: http://imgur.com/EX4aWIp

Screenshot from retail: http://i.imgur.com/UlY1L5e.jpg

Coordinates: X: 101.357353 Y: 4335.578613 Z: 101.465500
NPC Info: ENtry: 18758, GUID: 67032, Name: Telhamat Protector

**Comment by Oriden** [comment]
Fixed
