### ISSUE TITLE
Honor Hold Scout (Shatter Point)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#339]
The Honor Hold Scout at Shatter Point, Hellfire Peninsula is currently missing its patrol point around the tower on the floating island.

Coordinates: X: 284.307404 Y: 1462.054077 Z: -11398916
NPC Info: Entry: 20238, GUID: 71924, Name: Honor Hold Scout

**Comment by Pragma8123** [comment]
Fix submitted, check next restart

**Comment by Jiinkey** [comment]
Doesn't patrol still.

**Comment by Pragma8123** [comment]
Fixed
