### ISSUE TITLE
[Creature/Loot] Bleeding Hollow Scryer

### ISSUE THREAD

**Issue by LightningBlade** [NetherstormTeam/IssueTracker#34]
Creature Entry: 17478

The NPC is located within Ramparts, and on normal difficulty drops level 68 item(s)

**Comment by Clearlysql** [comment]
What item did you loot? I can't find anything in the DB that seems wrong at first glance.

**Comment by JppTheInsane** [comment]
http://www.wowhead.com/npc=17478/bleeding-hollow-scryer#drops:mode=heroic:0-1-19
Most of the grey items listed here.

**Comment by LightningBlade** [comment]
Conqueror's Vambraces of  the Champion - http://tbc.openwow.com/item=25013

**Comment by LightningBlade** [comment]
Could be that the loot is a "referenced" loot, so that multiple NPCs share it, and you wont be able to see the actual items in the creature_loot_template, then you'll have to look at reference_loot_template I believe it's called

**Comment by Clearlysql** [comment]
Went through all mobs (except the bosses) and removed reference loot from HC.

List of ID's I removed loot from, for the curious and in case I missed something:
17478
17269
17309
17270
17517
17259
17280
17281
17264
17271
17732
