### ISSUE TITLE
Murkblood Scavenger and Murkblood Raider

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#344]
According to WoWHead.com there should be 22 _Murkblood Scavenger's_ and 20 _Murkblood Raider's_ in Sunspring Post but there is alot less of them.

**Comment by Jiinkey** [comment]
This is definetly true. 

By the first building when entering the village, there is three Murkblood Scavengers Missing, and on the other side of this house, a murkblood putrifier is missing.

Screenshot: http://i.imgur.com/zMcOL0t.jpg
Screenshot: http://i.imgur.com/qmpwKrP.jpg

Moving further down, theres three more missing near the broken house to the left.

Screenshot:http://i.imgur.com/eTaRjRj.jpg

On the other side of the same broken building, another three scavengers along with a Murkblood Putrifier is missing.

Screenshot: http://i.imgur.com/tWlGuOv.jpg

Near the Kurenai Captive, there is two Murkblood Brutes missing.

Screenshot: http://i.imgur.com/GDEwGje.jpg

Outside the house with the captive, there is a murkblood raider guarding the door.

Screenshot: http://i.imgur.com/tpOG0nF.jpg

Outside this house with the Kurenai Captive inside, there is three more Scavengers missing.

Screenshot: http://i.imgur.com/F3OYMJa.jpg

Outside of the main building, there is two groups of three Scavengers missing.

Screenshot: http://i.imgur.com/GwlDqJv.jpg

Outside of the side entrance to the main building, a Murkblood Raider is missing.

Screenshot: http://i.imgur.com/oPOh9Da.jpg

On the other side, (Other side entrance) another raider is missing.

Screenshot: http://i.imgur.com/89LTz7T.jpg

To the left of the main entrance of the main building, there is a murkblood raider missing, this guy is looking over 3 more scavengers.

Screenshot: http://i.imgur.com/Q7H6Upf.jpg
Screenshot: http://i.imgur.com/MMVWyhL.jpg

Near the lake theres two small hills, theres two murkblood putrifiers, but one is missing.

Screenshot: http://i.imgur.com/FUIJZ5P.jpg

**Comment by Jiinkey** [comment]
Fixed.
