### ISSUE TITLE
Sunspring Villager's

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#345]
_Sunspring Villager's_ have 5,186 HP and they should have 3,820.

Entry: 18240, GUID: 84454, Name: Sunspring Villager

I don't know why they even have HP when they are corpses.

**Comment by Jiinkey** [comment]
Note: HP in this case is irrelevant, ignore the ammount of hp they have and make them appear dead instead.

**Comment by Jiinkey** [comment]
Fixed.
