### ISSUE TITLE
[Core/Bosses] Watchkeeper Gargolmar

### ISSUE THREAD

**Issue by Nevarian** [NetherstormTeam/IssueTracker#35]
"Back off, pup!" - Must charge the player first... Not just turn around, do a hit emote and then throw back the player.

**Comment by Blumfield** [comment]
@JppTheInsane mind taking a look at this ?

**Comment by JppTheInsane** [comment]
**After Some Testing**
Damage and knockback work.

The charge animation is the only thing missing. So it is merely a visual issue.

The visual works if it is casted as a player but not as a creature.

Need to do some more research to figure out why it doesn't work for creatures.

**Comment by jameyboor** [comment]
Visuals for creature charges should now work.
