### ISSUE TITLE
[Gossip Text] Wanted Poster (Zabra'jin)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#360]
The Wanted Poster is supposed to say:
"Shadow Hunter Denjai uses this board to post important announcements and news of bounties on the foes of Zabra'jin."
upon interaction.

Screenshot: http://i.imgur.com/w8Wviq2.jpg

22646, Entry 182165 - [Wanted Poster X:281.859009 Y:7866.529785 Z:23.857599 MapId:530]

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Fixed. Closing
