### ISSUE TITLE
Floating Skull Friendly to Alliance

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#366]
The Floating Skull at Reaver's Fall, Hellfire Peninsula is currently friendly with Alliance, its supposed to be hostile.

Screenshot: http://i.imgur.com/RkQJnV3.jpg

NPC: http://tbc.openwow.com/npc=21365

Coordinates: X: 21.038136, Y: 2102.802734, Z: 132.985291
NPC Info: Entry: 21365, GUID: 200010, Name: Floating Skull

**Comment by Clearlysql** [comment]
Test after restart.

**Comment by Jiinkey** [comment]
Works.
