### ISSUE TITLE
[Scripts/HellfireRamparts] Watchkeeper Gargolmar does not use Surge on the target farthest away.

### ISSUE THREAD

**Issue by JppTheInsane** [NetherstormTeam/IssueTracker#37]
Link to NPC:
http://tbc.openwow.com/npc=17306

Link to Spell:
http://tbc.openwow.com/spell=34645

Currently Watchkeeper Gargolmar uses Surge on a random target. He should be using Surge on the target farthest away.

**Comment by Blumfield** [comment]
there's an issue here #35

**Comment by JppTheInsane** [comment]
While they are related, it is two different issues.

**Comment by Nevarian** [comment]
https://github.com/cmangos/mangos-tbc/pull/44 have you seen this?
