### ISSUE TITLE
Mag'har Refugee lying instead of sitting

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#375]
As the title suggests, there is a Mag'har Refugee in Shattrath City that is currently lying down instead of sitting up.

Screenshot: http://i.imgur.com/p6bTrh5.jpg

Screenshot from retail: http://i.imgur.com/Id6INNl.jpg

Coordinates: X: -1602.635864, Y: 5347.262695, Z: -40.209213
NPC Info: Entry: 19144, GUID: 68466, Name: Mag'har Refugee

**Comment by LightningBlade** [comment]
fixed

**Comment by Jiinkey** [comment]
http://i.imgur.com/Vc4FfhY.jpg

even though its closed and fixed, updating with correct retail screenshot for future reference.
