### ISSUE TITLE
Andrion Darkspear

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#377]
Andrion Darkspear in Lower City, Shattrath City is currently offering to "I wish to unlearn Shadoweave Tailoring" even though the player doesn't have Shadoweave Tailoring.

Screenshot: http://i.imgur.com/cTqlVHZ.jpg

Coordinates: X: -2066.688477, Y: 5265.037109, Z: -38.464695
NPC Info: Entry: 22212, GUID: 77876, Name: Andrion Darkspinner

**Comment by Oriden** [comment]
The menu option doesn't seem to work aswell.

**Comment by Oriden** [comment]
Fixed. Also fixed the unlearn option aswell :)
