### ISSUE TITLE
[Creature/Linking] Flamewaker Imp

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#39]
The Flamewaker imp and the Heckling Fel Sprite are supposed pull as a group

**Comment by Clearlysql** [comment]
Seems like this applies to not only those mobs but to all mobs in the game when pulled by ranged attacks. This needs some more testing.

**Comment by Clearlysql** [comment]
Test this after next restart.

**Comment by Clearlysql** [comment]
Fixed. Can be improved later on but it works just fine as it is now.
