### ISSUE TITLE
Orb of Translocation (Firewing Point)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#395]
Similair to the Orb of Translocation in Falcon Watch, Hellfire Peninsula, the Orb of Translocation at Firewing Point, Terokkar Forest is not working either.

Screenshot: http://i.imgur.com/OZhQpAs.jpg

23159, Entry 182543 - [Orb of Translocation X:-2245.110107 Y:3124.270020 Z:27.388800 MapId:530]

**Comment by Jiinkey** [comment]
#311

**Comment by Pragma8123** [comment]
Fixed
