### ISSUE TITLE
[Creature/AI] Bleeding Hollow Tormentor #19424 Dismount on aggro

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#40]
Coordinates:
 X: -952.365540, Y: 2204.890137, Z: 9.906612
NPC Info: Entry: 19424, GUID: 69480, Name: Bleeding Hollow Tormentor

The orc is supposed to dismount and spawn his mount as an extra npc (couldnt get NPC Info since they didnt spawn).

**Comment by Sdyessdev** [comment]
Same issue as https://github.com/NetherstormTeam/IssueTracker/issues/20

**Comment by Clearlysql** [comment]
Added event AI for dismount, made sure the NPC spawns its pet as well which works fine already.
