### ISSUE TITLE
[Hunter/Pet]

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#42]
It seems you&#39;re unable to send your pet onto targets that are not in line of sight of the pet. This is atleast the case with mobs near the large armbolt thingies next to Thrallmar in Hellfire Peninsula.

Additionally, when using the ability Eye of the Beast, you&#39;re unable to attack with your pet when it&#39;s in Passive Stance.

**Comment by Jiinkey** [comment]
Update to this issue: This is not just in Hellfire near Thrallmar, this is everywhere, using pets/sending them into attack crashes the server and the pet doesn't even attack in the process.

**Comment by jameyboor** [comment]
Alright,I'll take a look at it, thanks.

**Comment by jameyboor** [comment]
Fixed.
