### ISSUE TITLE
Crippler

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#422]
The Crippler in Bone Wastes, Terokkar Forest seems slightly off visually when comparing our version with retail screenshots. The retail version has a shadowy aura around him, where as ours does not.

Screenshot: http://i.imgur.com/hAU46ex.jpg

      Coordinates: 
      X: -3355.032471, Y: 4311.730469, Z: -19.692812
      NPC Info: 
      Entry: 18689, GUID: 99283, Name: Crippler

http://www.wowhead.com/npc=18689/crippler#screenshots:id=226123

Also it seems that when you exit combat with him, for any reason (i died), then he runs alot of way points back, instead of returning to his nearest waypoint. 

Screenshot: http://i.imgur.com/u79IP53.jpg

**Comment by Clearlysql** [comment]
Could QA bring me a screenshot from retail where this NPC is targeted, to see if any aura is visible, and if so do hover over it so I know what aura it is. Would help a bit.

**Comment by Jiinkey** [comment]
https://www.youtube.com/watch?v=aUKuOHHBEww

Doesnt have any visible buff, or aura. Must be shadowform aura or something similair.

**Comment by Clearlysql** [comment]
Check after next restart and see if it's good enough.

**Comment by Jiinkey** [comment]
Fixed
