### ISSUE TITLE
Skywing (Skywing)

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#438]
For the quest offered by Skywing, called Skywing, you are supposed to escort and follow Skywing through Veil Shalas, however the lil' birdie seems to be missing all of his waypoints, allowing the player to not complete the quest. 

Screenshots: http://imgur.com/a/OuzNP

Video of how it's supposed to play out: http://www.wowhead.com/quest=10898/skywing#videos:id=84298

    Coordinates:
    X: -3608.745850, Y: 4173.494629, Z: 0.302609
    NPC Info:
    Entry: 22424, GUID: 78781, Name: Skywing

**Comment by jameyboor** [comment]
Fixed.
