### ISSUE TITLE
[Creature/Linking] Eye of Grillok #19440 Pulling associated summoner

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#44]
Coordinates:
X: -1032.386108, Y: 2103.223389, Z: 62.634335
NPC Info:
Entry: 19440, GUID: 69632, Name: Eye of Grillok

The NPC is supposed to be associated with another NPC(Entry: 19422, GUID: 69452, Name: Bleeding Hollow Necrolyte) when the Eye is pulled its supposed to call the Necrolyte to come fight with it.

**Comment by Clearlysql** [comment]
Is each Eye of Grillok associated with a specific Necrolyte? If so, would it be too much trouble to write a list of the GUID's of the NPC's that should be linked? (Like: Eye: <GUID> - Necrolyte: <GUID>)

**Comment by Sdyessdev** [comment]
Can't duplicate on retail. Closed.
