### ISSUE TITLE
Cabal Skirmisher

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#442]
There is a Cabal Skirmisher randomly standing by a Netherweb Victim in Netherweb Ridge, Terokkar Forest. It is not a spawnpoint that is supposed to be there, and I feel like he might've been spawned by one of the Netherweb Victim cocoons, but he is not supposed to be there atleast.

Screenshot: http://i.imgur.com/qvy6jkO.jpg

    Coordinates:
    X: -3814.829834, Y: 4230.295410, Z: 4.604908
    NPC Info:
    Entry: 21661, GUID: 75712, Name: Cabal Skirmisher

**Comment by Clearlysql** [comment]
This could be a result of the NPC the cocoon spawns, spawns permanently.

**Comment by Jiinkey** [comment]
Fixed.
