### ISSUE TITLE
Getting next quest from questline without completing reqs.

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#455]
_Entry: 21797, GUID: 86139, Name: Ancient Shadowmoon Spirit_

You shouldn't be able to take the quest _Teron Gorefiend, I am..._ without turning in:
_Divination: Gorefiend's Armor(ID 10634)
Divination: Gorefiend's Cloak(10635)
Divination: Gorefiend's Truncheon(10636)_

but you can get it by turning only 1 of these.

**Comment by Clearlysql** [comment]
Test after restart.
