### ISSUE TITLE
Earthmender Torlok

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#461]
_Entry: 21024, GUID: 73834, Name: Earthmender Torlok_

When you come to turn in the quest _The Hand of Guldan_ and when you speak to him you should be redirected to quest but instead he have gossiptext and then you can click on quest.

**Comment by Clearlysql** [comment]
You need to be a bit more specific. Provide Quest ID as well as screenshots of what's going on.
