### ISSUE TITLE
Hellfire Watcher's // Watchkeeper Gargolmar

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#477]
The Hellfire Watchers during the Watchkeeper Gargolmar seems to be slightly bugged in multiple ways, they are meant to follow their master closer than they are right now (he is walking abit to far ahead of them), and they seem to not be healing as much as they should be, the bosses health bar barely moves whenever they get a heal off, and the fight should feel alot harder than it currently does.

    Coordinates:
    X: -1226.905518, Y: 1453.708252, Z: 68.582504
    NPC Info:
    Entry: 17309, GUID: 62088, Name: Hellfire Watcher

    Coordinates:
    X: -1228.489746, Y: 1454.203491, Z: 68.582504
    NPC Info:
    Entry: 17309, GUID: 62089, Name: Hellfire Watcher

Spells: http://www.wowhead.com/npc=17309/hellfire-watcher#abilities

**Comment by Sdyessdev** [comment]
Healers are supposed to heal about 10% of his health, which stands around 3300HP. Working as intended.
