### ISSUE TITLE
[Creature/Behaviour] Evade when no path

### ISSUE THREAD

**Issue by Nevarian** [NetherstormTeam/IssueTracker#48]
Let's say... You stand on the ground, the creature is attacking you. You jump on top of a house. The creature now can't reach you no matter what. Instead of just going home, it should stand closest to the player and be in "evade" mode.

HOWEVER! If there's another player in the threatlist that's has an available path, the creature should attack him.

This is how I remember it was and I'm 90% sure, if someone can confirm or deny I'd be super happy :-)

**Comment by Clearlysql** [comment]
I remember something like this as well (having played retail from about a month or two before the release of TBC up until a few months after the release of WotLK) I remember jumping and climbing around Deadmines and this happened quite a lot with all of the melee NPC's but not with the ranged ones. So I'm willing to back you up on this.

**Comment by jameyboor** [comment]
Actually, according to videos and the core TODO comments, it's just a timer. After a few seconds ( I currently added it as 7 ) the creature should still reset and evade, in those 7 seconds the creature will "should stand closest to the player" Please re-open if you don't think this is valid.
