### ISSUE TITLE
Desolace Flame Keeper

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#556]
The Desolace Flame Keeper at Shadowprey Village, Desolace is supposed to have 3524 HP, but currently stands at only 1 health.

    Coordinates:
    X: -1844.065430, Y: 3057.906738, Z: 0.026328
    NPC Info:
    Entry: 25928, GUID: 86629, Name: Desolace Flame Keeper

https://db.ezwow.org/?npc=25928

**Comment by Pragma8123** [comment]
Check on restart

**Comment by Jiinkey** [comment]
still has only 1hp.

**Comment by Pragma8123** [comment]
Pssst @jameyboor

**Comment by Jiinkey** [comment]
Fixed.
