### ISSUE TITLE
Escape from Umbrafen - Spawns friendly Mobs

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#56]
Quest ID: 9752
Quest Name: Escape from Umbrafen

It&#39;s an escort quest, and it spawns friendly mobs. Pretty damn easy!

**Comment by Clearlysql** [comment]
Require ID's on these mobs.

**Comment by Nicko11** [comment]
Umbrafen Slavebinder - ID: 18042

**Comment by Clearlysql** [comment]
Fixed faction.
