### ISSUE TITLE
Balance Must Be Preserved - Not available to your race

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#60]
http://picpaste.com/uTr2bKzC.png

QuestID: 9720

Doesn&#39;t allow me to get the quest, due to some sort of racism.

**Comment by Ophinkey** [comment]
It seems that this quest has been completely removed from the questtable of the character first used to try and pick it up rendering the player completely unable to pick up and complete the quest at all.

-Ophius

**Comment by Ophinkey** [comment]
Same bug happens on an Orc, not just a troll.
Tried to pick up the quest, I get the error message in chat, and then the quest completely dissapears from the questgiver.

Screenshot: http://i.imgur.com/NGhEfdx.jpg

-Ophius

**Comment by Clearlysql** [comment]
Fixed.
