### ISSUE TITLE
Marsh Lurker - Stuck / LoS

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#61]
http://picpaste.com/qhH5WHmS.png

Name: Marsh Lurker
MobID: 18136

Coords: X: -1206.596680 Y: 5729.804199 Z: 49.093380

**Comment by Clearlysql** [comment]
Does this apply for all Marsh Lurkers or just a specific one? If just one, could you please include the GUID of it? Thanks.

**Comment by LightningBlade** [comment]
I remember this happening on another private server as well, it is this one specificly

**Comment by Nicko11** [comment]
GUID: 94845

**Comment by Clearlysql** [comment]
Fixed spawnpoint, which was previously outside of textures above where the creature appeared. Should be fully functional after restart, please check this later on.

**Comment by LightningBlade** [comment]
Fixed in latest Updates

-Creidts: Clearlysql
