### ISSUE TITLE
Enraged Fire Spirit

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#659]
_Entry: 21061, GUID: 74016, Name: Enraged Fire Spirit
Coordinates:X: -3828.922363, Y: 1480.632080, Z: 42.758236_

They should cast _Fel Fireball_ spell on you and also according to WoWHead he have _Enrage_ and _Fel Fire Aura_ which I didn't see on retail.

http://www.wowhead.com/npc=21061/enraged-fire-spirit#abilities

https://s31.postimg.org/klgp9hq0b/Wo_WScrn_Shot_062616_120112.jpg

**Comment by Blumfield** [comment]
Does he cast Enraged at a certain hp % ? I can't seems to find any info on that

**Comment by Blumfield** [comment]
Fixed, report feedback when it's live on PTR
