### ISSUE TITLE
Burstcap Mushrooms, Mon! Respawns to fast, doesn&#39;t despawn when looted

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#66]
Quest ID: 9814

It doesn&#39;t despawn the object when looted, and is lootable again within 30 seconds.

Coordinates:
X: 190.149246 Y: 8008.206543 Z: 21.703926

**Comment by Clearlysql** [comment]
Restock timer is set to 30 seconds thus it does not despawn. I need confirmation that this object should indeed disappear after being looted, which would make sense. But I'd still like confirmation on this.

**Comment by Clearlysql** [comment]
Now makes the visual effect it's supposed and despawns.
