### ISSUE TITLE
Gul'dan

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#660]
_Coordinates: X: -3592.615967, Y: 1851.469482, Z: 47.240585
Entry: 17008, GUID: 84600, Name: Gul'dan_

He should be kneeling and he is standing instead,
Also there is purple circle around him that should pulse and then dissapear then again appear.

https://s31.postimg.org/6h3bxhnjv/Wo_WScrn_Shot_062616_132336.jpg
https://s31.postimg.org/7xeufmqgr/Wo_WScrn_Shot_062616_132351.jpg

**Comment by Jiinkey** [comment]
I cannot for the life of me replicate the pulsing aura on retail on my pc. But i submitted a fix for the kneeling now.

**Comment by Jiinkey** [comment]
Fixed.
