### ISSUE TITLE
Have You Ever Seen One of These? - Murlocs not spawning / Working

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#68]
http://picpaste.com/CtaYPDKq.png

QuestID: 9816

Puts down the cage, one murloc seems to spawn and then disappear, having the quest not being completed.

-Nicko

**Comment by Clearlysql** [comment]
I could hackfix this but I would prefer not to. There's insufficient information in the database for me to be able to figure out what's going on with this quest and I require the assistance of a core dev for this.

**Comment by Clearlysql** [comment]
Added kill credit on event trigger. It now works.
