### ISSUE TITLE
[Spell/System] Spell Stacking

### ISSUE THREAD

**Issue by Sdyessdev** [NetherstormTeam/IssueTracker#7]
Mark of the wild and Gift of the wild stack on top of each other. Same effect, one is just used for a group buff rather than single buff.

Should override each other.

Another is that Thunder Clap and Slice and Dice will not stack. If thunder clap is active on the target a rogue cannot use slice and dice.

**Comment by Sdyessdev** [comment]
Have fun m8

**Comment by jameyboor** [comment]
Skyler was lying.
