### ISSUE TITLE
Jumping underwater instead of swimming upward when clicking spacebar

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#72]
When spacebar is hit while underwater, the character jumps upward, as if on dry land, instead of swimming upward.

Video attached: https://www.youtube.com/watch?v=-yBx_6XGv40
(video is private, only people with the link will be allowed to watch, so no one that is not invited on will be able to see or comment)

**Comment by Clearlysql** [comment]
After some research it turns out this is how it should be.
