### ISSUE TITLE
Nether Ray mana draining targets other than the main target

### ISSUE THREAD

**Issue by bonkeymone** [NetherstormTeam/IssueTracker#723]
Nether Ray in Netherstorm is draining totems when they have no mana nor are they the main target. This could point to maybe an aggro issue as well? 

Bug info for Nether Ray:
  Coordinates: X: 3370.808105, Y: 3931.292725, Z: 202.007446
  NPC Info: Entry: 18880, GUID: 67681, Name: Nether Ray

**Comment by Jiinkey** [comment]
http://tbc.openwow.com/npc=18880

http://tbc.openwow.com/spell=17008

**Comment by Pragma8123** [comment]
This seems to be because the target type in the EventAI entry is 4 (TARGET_T_HOSTILE_RANDOM) which selects any hostile target i.e. a hostile totem.
