### ISSUE TITLE
Area 52 inkeeper does not offer items.

### ISSUE THREAD

**Issue by bonkeymone** [NetherstormTeam/IssueTracker#725]
Area 52 inkeeper Remi Dodoso does not offer usual items such as food and water.

buginfo:
Coordinates: X: 3062.662109, Y: 3697.728516, Z: 142.332489
NPC Info: Entry: 19571, GUID: 70010, Name: Innkeeper Remi Dodoso

**Comment by Jiinkey** [comment]
Looking at http://tbc.openwow.com/npc=19571 she doesn't offer anything either. Checking retail, she doesn't offer anything there aswell. Seems like its intended.
