### ISSUE TITLE
[Quest] Mark V is alive!

### ISSUE THREAD

**Issue by bonkeymone** [NetherstormTeam/IssueTracker#726]
Quest impossible to complete. The mob that you escort, Maxx A. Million Mk. V, resets his path and runs back to the starting point after exiting combat. He does come back and attempt to continue the quest if you follow him back to the starting point, but the mobs will respawn which starts a never ending circle.

Buginfo:

Coordinates: X: 3376.327148, Y: 3713.734863, Z: 142.986694
NPC Info: Entry: 19589, GUID: 70021, Name: Maxx A. Million Mk. V

**Comment by jameyboor** [comment]
Fixed.
