### ISSUE TITLE
Eclipsion Cavalier

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#727]
```
Coordinates:    X: -4282.487305, Y: 1387.263672, Z: 140.687012
Entry: 22018, GUID: 77168, Name: Eclipsion Cavalier
```

They should be riding on Hawkstrider's and after you kill the _Eclipsion Cavalier_ he should cast _Summon Eclipsion Hawkstrider_ (ID 38311) and summon _Eclipsion Hawkstrider_ for you to kill.

http://wow.zamimg.com/uploads/screenshots/normal/52104-eclipsion-cavalier.jpg

**Comment by Blumfield** [comment]
Fixed, check back when it's live on ptr

**Comment by disastrous94** [comment]
He have Hawkstrider now but he dosen't summon him when he die.Still need fixing

**Comment by Blumfield** [comment]
It's not live yet

**Comment by disastrous94** [comment]
still now working

**Comment by disastrous94** [comment]
Fixed!
