### ISSUE TITLE
Chancellor Bloodleaf and Corok the Mighty

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#728]
```
Coordinates: X: -4503.054199, Y: 1318.773682, Z: 124.852783
Entry: 22012, GUID: 77087, Name: Chancellor Bloodleaf

Coordinates: X: -4503.054199, Y: 1318.773682, Z: 124.852783
Entry: 22011, GUID: 77086, Name: Corok the Mighty
```

These two are part of the quest _Blood Elf + Giant = ???_ (ID 10744) 
Chancellor Bloodleaf should cast spells Arcane Explosion(34517) and Arcane Missiles(15791)
http://tbc.openwow.com/npc=22012#abilities

Corok the Mighty should cast spells Stomp(12612) and Trample(15550)
http://tbc.openwow.com/npc=22011#abilities

**Comment by Blumfield** [comment]
Fixed, check back when it's live on PTR

the arcane missiles part is kind of weird but apparently it's not the only one using this spell that way

**Comment by disastrous94** [comment]
still now working!

**Comment by disastrous94** [comment]
Fixed
