### ISSUE TITLE
Illidari Watcher

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#729]
```
Coordinates: X: -4597.266602, Y: 1339.971069, Z: 139.461990
Entry: 22093, GUID: 77533, Name: Illidari Watcher
```

First of all they should have some aura on them to make them look like they have some kind of shadow form.(Sry don't have more info on that)
Screenshoot:
http://wow.zamimg.com/uploads/screenshots/normal/33727-illidari-watcher.jpg

They should cast spell _Mortal Strike_(32736)

**Comment by Jiinkey** [comment]
#422

**Comment by Blumfield** [comment]
http://i.imgur.com/L4Slf8E.png
Left = shadow aura applied
Right = untouched

Does this looks to you ? (the spell part is fixed)

**Comment by disastrous94** [comment]
looks fine to me

**Comment by Blumfield** [comment]
Fixed, check back when it's live on PTR

**Comment by disastrous94** [comment]
Checked!
