### ISSUE TITLE
Elder Kuruti standing/sinking into the floor of his building

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#73]
Elder Kuruti in Feralfen Village in Zangarmarsh sinks through the floor with his feet not standing entirely on the floor of the building.

Coordinates:
X: -372.360565, Y: 7255.420898 Z: 54.773003

NPC Info:
Entry: 18197, GUID: 64975, Name: Elder Kuruti

Screenshot link: http://i.imgur.com/6GyQOPC.jpg

**Comment by Clearlysql** [comment]
Fixed spawnpoint.
