### ISSUE TITLE
[Gossip Text] Caza'rez

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#730]
Caza'rez in Thrallmar, Hellfire Peninsula is missing his gossip text. However getting to it might not be so easy. He is no longer placed in Thrallmar on retail, he is inside of the Hellfire Peninsula instances instead as a questgiver. Needs research.

    Coordinates:
    X: 238.759247, Y: 2706.166260, Z: 89.759338
    NPC Info:
    Entry: 17558, GUID: 63166, Name: Caza'rez

**Comment by Sdyessdev** [comment]
Same quests, new location. Let's assume gossip text is the same.

**Comment by Sdyessdev** [comment]
Fixed
