### ISSUE TITLE
Thrallmar Grunts 

### ISSUE THREAD

**Issue by Jiinkey** [NetherstormTeam/IssueTracker#731]
The Thrallmar Grunts near the tower in Thrallmar is currently not a part of the thrallmar faction as they're supposed to be.

Screenshot: http://i.imgur.com/gpMQsDH.jpg

    Coordinates:
    X: 218.532486, Y: 2805.369629, Z: 129.557037
    NPC Info:
    Entry: 16580, GUID: 57504, Name: Thrallmar Grunt

    Coordinates:
    X: 218.532486, Y: 2805.369629, Z: 129.557037
    NPC Info:
    Entry: 16580, GUID: 57508, Name: Thrallmar Grunt

**Comment by Jiinkey** [comment]
Okay, scratch that, goes for all the grunts.

**Comment by Jiinkey** [comment]
And the marksmen.

    Coordinates:
    X: 101.773422, Y: 2722.052002, Z: 90.549797
    NPC Info:
    Entry: 16582, GUID: 57551, Name: Thrallmar Marksman

**Comment by Sdyessdev** [comment]
Fixed
