### ISSUE TITLE
Dragonmaw Peon

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#753]
```
Coordinates:X: -4932.934570, Y: 371.122314, Z: 84.903885
Entry: 22252, GUID: 78029, Name: Dragonmaw Peon
```
They are hostile and when they attack you get aggro but they don't use attack.
Also they should cast _Sunder Armor_ ID 15572

https://s32.postimg.org/l5ly2too5/Wo_WScrn_Shot_070816_221305.jpg

**Comment by Blumfield** [comment]
Fixed

**Comment by disastrous94** [comment]
Is this live?
