### ISSUE TITLE
Shadowmoon Chosen

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#760]
```
Coordinates: X: -3338.224854, Y: 453.760834, Z: 99.813393
Entry: 22084, GUID: 77501, Name: Shadowmoon Chosen

```

They should cast spells _Uppercut_ ID 10966 and _Whirlwind_ ID 38618.
According to OpenWoW there are two Whirlwind spells that he should cast so don't know which one is right.

http://tbc.openwow.com/npc=22084#abilities

**Comment by Blumfield** [comment]
Whirlwind ID 38619 is the trigger of Whirlwind ID 38618, he only cast 2 spells, fixed check back when it's live on ptr

**Comment by disastrous94** [comment]
Checked
