### ISSUE TITLE
Shadowmoon Darkweaver

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#761]
_Coordinates: X: -3270.463135, Y: 463.006195, Z: 103.943985
Entry: 22081, GUID: 77391, Name: Shadowmoon Darkweaver_

They should cast _Immolate_ ID 11962, _Nether Infusion_ ID 38446 and _Shadow Bolt_ ID 9613

http://tbc.openwow.com/npc=22081#abilities

**Comment by Blumfield** [comment]
Fixed, check back when it's live on ptr

**Comment by disastrous94** [comment]
Checked!
