### ISSUE TITLE
Totems have wrong display ids.

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#783]
When you use totems as horde they look like alliance totems.

https://s32.postimg.org/mhraenilx/Wo_WScrn_Shot_071016_144712.jpg

They should looks like this:
http://vignette4.wikia.nocookie.net/wowwiki/images/0/02/Totem1.jpg/revision/latest?cb=20050209114712

**Comment by Sdyessdev** [comment]
Fixed
