### ISSUE TITLE
Swimming while dead

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#792]
While you are dead you are suppose to walk on all watery surfaces but here I am dead in lava lake in SMV and instead of walking on it my char is swimming.

https://s32.postimg.org/yxbij3h2d/Wo_WScrn_Shot_071616_100447.jpg

**Comment by Jiinkey** [comment]
99% sure you dont get WATERwalking on lava.

**Comment by disastrous94** [comment]
You don't but while you are dead you can walk on it.

**Comment by Clearlysql** [comment]
You've never been able to walk on lava while being a ghost. Only on water.
