### ISSUE TITLE
Sunfury Geologist

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#802]
```
Coordinates: X: 2999.410400, Y: 4112.745605, Z: 154.114395
Entry: 19779, GUID: 70732, Name: Sunfury Geologist
```
Missing 2 spells:
_Puncture Armor_ ID 35918
_Throw Rock_ ID 36645

http://tbc.openwow.com/npc=19779#abilities

**Comment by Blumfield** [comment]
https://streamable.com/9vxp works for me
