### ISSUE TITLE
Overseer Athanel

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#815]
```
Coordinates: X: 2912.582520, Y: 2140.801758, Z: 163.920456
Entry: 20435, GUID: 72401, Name: Overseer Athanel
```

He is missing his spell _Cleave_ ID 15496.
http://tbc.openwow.com/npc=20435#abilities

**Comment by Clearlysql** [comment]
He also charges, which is not described on WoWHead nor OpenWoW.
