### ISSUE TITLE
[Creature/Vendor] "This merchant doesn't like you"

### ISSUE THREAD

**Issue by Nevarian** [NetherstormTeam/IssueTracker#86]
If you run towards a vendor (while being out of range) while clicking him, you will get the error message "This merchange doesn't like you" while you're moving towards him. It's like that for all vendors in the human starting area atleast. Some vendors doesn't produce the error message, but still refuses to open the vendor window.

GIF:
https://gyazo.com/9bfe0eefb308ee25dd00d3fa2b9c7fe5

SS:
https://gyazo.com/2e718d81dc2a29af844818d60abccf10

**Comment by Clearlysql** [comment]
This occurs in a very small span where you're right on the edge but inside the zone where you can interact with the NPC, but having just entered it. I would assume it might have something to do with server delay. Once you're closer to the NPC you can interact with him just as normal despite moving, so this ONLY occurs while running from outside the interaction zone, into it and trying to interact with the NPC right after getting in range.

**Comment by Sdyessdev** [comment]
I like this one. We should keep it.

Is "You are too far away" the blizzlike result? Dunno if that existed for TBC

**Comment by Sdyessdev** [comment]
Some more research...

Apparently this also happens on Trinitycore. Gonna take a bit of a rework, but we can fix it.
