### ISSUE TITLE
[Spell/Buffs] Lower Rank Override Higher Rank

### ISSUE THREAD

**Issue by LightningBlade** [NetherstormTeam/IssueTracker#88]
Greetings,

Casting a buff on a target, that already has the same buff, but a higher rank will override it.

How to Reproduce:
1. Use 2 Mages
2. Have Mage 1 buff himself with Arcane Intellect Rank 5 
3. Have Mage 2 buff Mage 1 with Arcane Intellect Rank 1

How it's supposed to work -
The player should be able to override his own buffs, but not others.

Example is, Mage 2 buffs Mage 1 with Arcane Intellect Rank 5, then Mage 1 should be able to Buff himself with Arcane Intellect Rank 1.

**Comment by jameyboor** [comment]
Apparently this is blizzlike in TBC, nevertheless I thought it was stupid and added a check for this.
