### ISSUE TITLE
Deadmines Bugs/Issues

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#90]
The first issue I came across in Deadmines was the Goblin Woodcarvers, they have a spell called Axe Toss which stuns their target for three seconds, however this spell doesnt have any stun animation and just freezes the target (the player) in place.

Screenshot: http://i.imgur.com/UtTRZIu.jpg

.buginfo of one of the Goblin Woodcarvers:
Coordinates: X: -291.065643 Y: -493.790375 Z: 50.028748
NPC Info: Entry: 641, GUID: 79231, Name: Goblin Woodcarver
____

The rarespawn issue is present in this instance too, three tries and the rarespawn was present every single time, i have screenshots from run number 2 and run number 3.

Screenshot run # 2: http://i.imgur.com/7Rw6yDY.jpg
Screenshot run # 3: http://i.imgur.com/n9POsBX.jpg
____
Goblin Craftsmen seem to have an incredibly high dropchance on Copper Ore, Rough Stone, And Coarse Blasting Powder

.buginfo of one of the Goblin Craftsmen:
Coordinates: X: -184.818604 Y: -569.121887 Z: 50.803757
NPC Info: Entry: 1731, GUID: 79199, Name: Goblin Craftsman
____

There seems to be patrols around the bossrooms of every boss that spawns unintentionally before the boss is killed, these are meant to be there after the boss dies, not before the boss is killed. 

Video from the Gilnid boss room: https://www.youtube.com/watch?v=zp8sWMXvQnk&feature=youtu.be

____

There seems to be a pathing issue in the Gilnid boss room (the big forge), where atleast two mobs go ontop and inside two anchors around the edge of the room.

Video: https://www.youtube.com/watch?v=99XmeWEVonI

,buginfo of the two mobs:

Coordinates: X: -213.870880 Y: -565.104614, Z: 20.976875
NPC Info: Entry: 1731, GUID: 79179 Name: Goblin Craftsman

Coordinates: X: -213.870880, Y: -565.104614 Z: 20.976875
Entry: 622, GUID: 79198, Name: Goblin Engineer
____

The Defias Miners/Defias Strip Miners seem to have an unusually high droprate on greens

Screenshot: http://i.imgur.com/7RjfiZ7.jpg
____

When looting the Defias Gunpowder, there is no elite spawned to attack the group, supposed to be spawning: http://wowwiki.wikia.com/wiki/Defias_Gunpowder
____

When firing the Defias Cannon the patrols that spawn stand run into the room and stand on top of eachother instead of standing next to eachother.

Video: https://www.youtube.com/watch?v=FDgqxqYn9Vw
____

The Defias Pirates and Defias Squallshaper seems to have a very high droprate of Coarse Stone, more or less every single one I kill has them in the loottable.

.buginfo on one of each of the mobs:
Coordinates: X: -53.703564 Y: -727.985779 Z: 9.240241
NPC Info: Entry: 657, GUID: 79300, Name: Defias Pirate

Coordinates: X: -53.703564 Y: -727.985779 Z: 9.240241
NPC Info: Entry: 1732, GUID: 79306, Name: Defias Squallshaper
____

During the Mr. Smite encounter, he stuns the group and runs towards his chest to change weapons, when he changes from the dual wield axes, to the two handed mace, the axes doesn&#39;t dissapear, but are sheathed on his sides and he is seen wearing the mace, and the axes simultaneously.

Screenshot: http://i.imgur.com/ENlnBGQ.jpg
____

Just before the Edwin Van Cleef encounter there is 2 Defias Blackguards standing outside his cabin on top of the boat, they are standing alot further from the cabin entrance, than they&#39;re supposed to.

Screenshot: http://i.imgur.com/wMkuUba.jpg (note: the mob died in the position it was standing in originally, I oneshot it so it never moved.)

Coordinates: X: -54.415703 Y: -810.044189 Z: 42.093269
NPC Info: Entry 636, GUID: 79383 Name: Defias Blackguard.

Note: The same goes for the mob standing on the other side of the cabin.
____

During the Edwin Van Cleef encounter he is supposed to summon Defias Blackguards to his aid, but the summon of the blackguards seem clunky and they come in packs instead of one by one (may have something to do with the ammount of damage i did to him)

____

**Comment by TheGreatFratsby** [comment]
Copper Ore drop % is not an error, thank you though!
![image](https://cloud.githubusercontent.com/assets/10408492/14770551/6401102e-0a42-11e6-8de5-2483039a087c.png)

**Comment by TheGreatFratsby** [comment]
Still working on this, schools finals are hitting so going a bit slow :D.

**Comment by Sdyessdev** [comment]
Fixed in 4421908bbc71e7f247c6c7944a0fe010bd2761de
