### ISSUE TITLE
[Spell/Mage] Blink is super wonky.

### ISSUE THREAD

**Issue by Clearlysql** [NetherstormTeam/IssueTracker#91]
Blink will teleport you under textures in certain areas such as Undercity (The Canals to be specific). I assume this has something to do with the fact that it snaps you back to the ground after blinking.

**Comment by Blumfield** [comment]
A fix has been commited, i'm not closing it yet, we'll need feedback once it's live on PTR

**Comment by Clearlysql** [comment]
Will test thoroughly once fix is live.

**Comment by Nevarian** [comment]
Cannot reproduce anymore.
