### ISSUE TITLE
Ornak Grimshot saying he cannot train me, even though im a hunter.

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#94]
As the title reads, Ornak Grimshot, the Orc hunter trainer in Orgrimmar, says: &#34;I can not train you.&#34; despite me being a hunter. I can still click &#34;I seek training in the ways of the Hunter.&#34; and &#34;I wish to unlearn my talents.&#34; however.

Screenshot: http://i.imgur.com/fRaMXw1.jpg

Coordinates: X: 2100.184326 Y: -4610.077148 Z: 58.506500
NPC Info: Entry: 3352, GUID: 7449, Name: Ornak Grimshot

-Ophius

**Comment by Clearlysql** [comment]
NPC text is missing from database. If anyone could get hold of what this NPC is supposed to say (both for hunters as well as for non-hunters) that would be appreciated. If there's nothing within a few days I will make a temp fix for this.

**Comment by Ophinkey** [comment]
Since we were not able to find any information about the text for Ormak on TBC we decided to test on retail, and this is the result we got:
http://i.imgur.com/i9hLnRW.jpg

-Ophius

**Comment by Sdyessdev** [comment]
Did anyone try checking a vanilla/TBC realm

**Comment by Clearlysql** [comment]
Yes, Ophinkey did a lot of research on other realms to see if anyone might've got it right. The only thing found was cheatfixes that brought you straight into the spell learning list or the same message. So we will go with the retail version until anyone manages to find anything to prove it should be different.

**Comment by Clearlysql** [comment]
Found confirmation in our DB. The texts were just not linked. The NPC now have the correct text.
