### ISSUE TITLE
Idols of the Feralfen way to little spawnpoints

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#99]
Feralfen Idols for the quest, Idols of Feralfen seems to have way to little active spawnpoints, we were only able to find two spawnpoints going through the area of Feralfen Village.

Screenshot of the two of the Idols we could find: http://i.imgur.com/1xISivs.jpg

Coordinates: X: -355.678238 Y: 7254.844238 Z: 50.171841

-Ophius

**Comment by Ophinkey** [comment]
Idols of the Feralfen: http://tbc.openwow.com/quest=9787
Feralfen Idols: http://tbc.openwow.com/item=24422

It is a quest where you are supposed to pick up 6 Idols off of the ground and turn them back in to the quest giver, it is supposed to have multiple spawnpoints throughout the Feralfen Village, but Nicko & I were only able to find the two Idols on the screenshot (Near Elder Kuruti).

-Ophius

**Comment by Clearlysql** [comment]
Contained in [object: 182139](www.wowhead.com/object=182139)

**Comment by Clearlysql** [comment]
Enough idols are already spawned, they're just difficult to spot sometimes.
